#version 460

//uniform float timer;

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding=1) buffer result {
    vec3 normals[];
};

float random(vec2 st)
{
    return fract(sin(dot(st.xy, vec2(12.9898,78.233))) * 43758.5453123);
}

void main() {
    for (int i = 0; i < 1000; i++){
        normals[i].x = random(vec2(i, 0));
        normals[i].y = random(vec2(i+1, 1));
        normals[i].z = random(vec2(i+2, 2));
    }
}